# Generated by Django 5.1.4 on 2024-12-11 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brandid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brands'),
        ),
    ]
