# Generated by Django 5.1.4 on 2024-12-13 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_brandid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='productparams',
            name='skuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sku'),
        ),
    ]
